### ISSUE TITLE
2020년 6월 4일 데일리 체크인

### ISSUE THREAD

**Issue by sigridjineth** [jypthemiracle/Today-I-Learned#35]
## 체크인
* 기상: 6시 30분
* 업무 시작: 7시 10분
* 체크인 작성: 8시 20분

## 오늘의 기분
* 11시에 자서 6시에 기상하는 것 나쁘지 않다. 7시간 취침 좋다 :)
* 6시에 일어나서 준비하면 7시에 투썸 카페로 떨어질 수 있다. 아주 합리적이고 효율적이다.
* 넥스터즈 모집공고를 접했다. 군대 가기 전에 마지막으로 하면 좋을 것 같은 활동이라 지원해보려고 한다.

## 오늘의 할 일
* [ ] (코드스쿼드) MySQL 공간 데이터 삽입해보기
* [x] (코드스쿼드) 오늘 호눅스 쿼리튜닝 수업 정리하기
* [x] (VHS) 정기수업 과제 피드백 및 제출하기
* [x] (설리번 프로젝트) 제 1회 웨비나 준비 및 진행하기
* [ ] (넥스트스텝) 3단계 로또 미션 피드백하고 수정하기

**Comment by realsigridjin** [comment]
위닝 오지게 했다
코딩은 하나도 안했다. -_-
