### ISSUE TITLE
2020년 6월 8일 체크인

### ISSUE THREAD

**Issue by sigridjineth** [jypthemiracle/Today-I-Learned#37]
# 2020년 6월 8일 월요일 체크인

## 체크인
* 기상 시간 08:00AM, 체크인 시각 09:30AM
* 밤에 푹 자서 컨디션 굿
* 딱히 별 생각 없다... 그저 입영통지서를 빨리 받고 싶다.

## 오늘 할 일
* [x] 설리번 프로젝트 남은 Pull Request 리뷰하기
* [x] Spring Boot GraphQL 튜토리얼
* [x] 호눅스 Auto Scaling 수업 수강/정리하기
* [x] 이슈관리 프로젝트 요구사항 분석 및 기술스택 합의
* [ ] MDM4U 과제 요구사항 분석 및 오늘 작성 어디까지 할 지 고민
* [ ] 넥스트스텝 로또 미션 마무리 및 사다리 미션 1단계 수행
* [ ] 넥스터즈 지원서류 작성하기 (포트폴리오 제외)

**Comment by realsigridjin** [comment]
Spring Boot GraphQL 튜토리얼: https://github.com/jypthemiracle/SpringBoot-GraphQL/tree/step3
