### ISSUE TITLE
[2020년 2월 26일 수요일] 데일리 스크럼

### ISSUE THREAD

**Issue by sigridjineth** [jypthemiracle/Today-I-Learned#4]
# 2020년 2월 26일 수요일
## 오늘의 일정
- 교보문고 가서 책 구매하기 - 토익, 텝스 등
- 코드스쿼드에서 오후 시간 학습하기
- 모두의연구소 풀잎스쿨 낯선수학 20:30-21:30
-> 부퍼실로서 줌 계정 on 해주어야 함
## 오늘의 할 일
- _서울외고 동아리 소개 글 남겨주기_ done.
- java-qna 스텝 2 완성하고, Pull Request 보내기
- _Elements of AI 번역 남겨둔 것 진행하기_ (어디다 링크를 둬야지) done.
- 토익, 텝스 3월 접수분 확인하기 -> 내일 접수하기
- _봉사활동 진행사항 확인하기_ -> 들어옴 done.
- _스프링 입문을 위한 자바 객체지향의 원리와 오해 1장_ done.

**Comment by realsigridjin** [comment]
밥 아이거가 은퇴했다. 후계자 구하기도 쉽지 않았다고 하는데 차기 CEO는 영업 쪽 하던 사람이다. 디즈니월드 이런.. 결국 IP가지고 더 재미를 보겠다는 심상일 듯하다.
https://thewaltdisneycompany.com/bob-chapek-named-chief-executive-officer-of-the-walt-disney-company/

**Comment by realsigridjin** [comment]
오늘은 어느 인스타 친구가 내 스토리를 캡쳐해서 고대 에타에 올림 푸하하
