### ISSUE TITLE
[2020.02.29-03.08] 코드스쿼드 방학기간 학습계획

### ISSUE THREAD

**Issue by sigridjineth** [jypthemiracle/Today-I-Learned#7]
# 2020년 2월 29일 - 3월 8일 방학기간 학습계획
### 우선순위 별로 나열, 절대 몰아서 하지 말고 계획대로 분산해서 학습할 것
* _리눅스마스터 2급 준비_ 취소됨
* 더 뉴 텝스 실전연습 500 문법/어휘 풀이
* java-qna Step3 마무리 (코딩은 하루에 2시간 씩)
* 해커스 TEPS 실전모의고사 풀이 후 학습

## 업무 필요사항
* _봉사활동 문의(3/3 활동, 3/1 도서관 문의)_ 완료
* 3/5 생일 프레젠뉴 추진완료
* _모두의연구소 풀잎스쿨 3월 1주차 발제 준비_
* 널채움 오픈데이터데이 준비하기

**Comment by realsigridjin** [comment]
outdated since lots of difficulties happen..
